<?php
/**
 * Branding Settings Helper Functions
 *
 * Provides centralized brand settings management with new structured format
 *
 * @package SubmittalBuilder
 * @version 1.1.0
 */

if (!defined('ABSPATH')) exit;

/**
 * Get default brand settings
 *
 * @return array Brand settings with company, visual, and meta keys
 */
function sfb_brand_defaults() {
  return [
    'company' => [
      'name'     => get_bloginfo('name'),
      'address'  => '',
      'phone'    => '',
      'website'  => get_site_url(),
      'logo_id'  => 0,
      'logo_url' => '',
    ],
    'visual' => [
      'primary_color'  => '#0E45E9', // modern_blue default
      'include_cover'  => true,
      'footer_text'    => 'Generated by Submittal & Spec Sheet Builder',
      'preset_key'     => 'modern_blue',
    ],
    '_meta' => [
      'version'    => '1.1.0',
      'updated_at' => current_time('mysql'),
    ],
  ];
}

/**
 * Sanitize brand settings input
 *
 * @param array $in Raw input data
 * @return array Sanitized brand settings
 */
function sfb_sanitize_brand_settings($in) {
  $defaults = sfb_brand_defaults();

  // Company data
  $company = [
    'name'     => sanitize_text_field($in['company']['name'] ?? $defaults['company']['name']),
    'address'  => sanitize_textarea_field($in['company']['address'] ?? $defaults['company']['address']),
    'phone'    => sanitize_text_field($in['company']['phone'] ?? $defaults['company']['phone']),
    'website'  => sanitize_text_field($in['company']['website'] ?? $defaults['company']['website']),
    'logo_id'  => absint($in['company']['logo_id'] ?? $defaults['company']['logo_id']),
    'logo_url' => esc_url_raw($in['company']['logo_url'] ?? $defaults['company']['logo_url']),
  ];

  // Visual settings
  $visual = [
    'primary_color' => preg_match('/^#([0-9a-f]{3}|[0-9a-f]{6})$/i', $in['visual']['primary_color'] ?? '')
                       ? $in['visual']['primary_color']
                       : $defaults['visual']['primary_color'],
    'include_cover' => !empty($in['visual']['include_cover']),
    'footer_text'   => sanitize_text_field($in['visual']['footer_text'] ?? $defaults['visual']['footer_text']),
    'preset_key'    => in_array($in['visual']['preset_key'] ?? '', ['modern_blue', 'architect_gray', 'engineering_bold', 'clean_violet', 'custom'])
                       ? $in['visual']['preset_key']
                       : 'custom',
  ];

  // Meta
  $meta = [
    'version'    => '1.1.0',
    'updated_at' => current_time('mysql'),
  ];

  return [
    'company' => $company,
    'visual'  => $visual,
    '_meta'   => $meta,
  ];
}

/**
 * Get brand settings (with fallback to old format for migration)
 *
 * @return array Brand settings
 */
function sfb_get_brand_settings() {
  $brand = get_option('sfb_brand_settings', null);

  // If new format exists, use it
  if ($brand !== null && isset($brand['company']) && isset($brand['visual'])) {
    // Ensure logo_url is populated if logo_id exists
    if (!empty($brand['company']['logo_id']) && empty($brand['company']['logo_url'])) {
      $logo_url = wp_get_attachment_image_url($brand['company']['logo_id'], 'full');
      if ($logo_url) {
        $brand['company']['logo_url'] = $logo_url;
      }
    }
    return $brand;
  }

  // Migration: Check old format and convert
  $old = get_option('sfb_branding', []);
  if (!empty($old)) {
    $migrated = [
      'company' => [
        'name'     => $old['company_name'] ?? get_bloginfo('name'),
        'address'  => $old['company_address'] ?? '',
        'phone'    => $old['company_phone'] ?? '',
        'website'  => $old['company_website'] ?? get_site_url(),
        'logo_id'  => 0, // Old format didn't store ID
        'logo_url' => $old['logo_url'] ?? '',
      ],
      'visual' => [
        'primary_color'  => $old['primary_color'] ?? '#0E45E9',
        'include_cover'  => $old['cover_default'] ?? true,
        'footer_text'    => $old['footer_text'] ?? 'Generated by Submittal & Spec Sheet Builder',
        'preset_key'     => $old['brand_preset'] ?? 'custom',
      ],
      '_meta' => [
        'version'    => '1.1.0',
        'updated_at' => current_time('mysql'),
        'migrated_from' => 'sfb_branding',
      ],
    ];

    // Save migrated data
    update_option('sfb_brand_settings', $migrated, false);

    return $migrated;
  }

  // Return defaults if nothing exists
  return sfb_brand_defaults();
}

/**
 * Get preset color mappings
 *
 * @return array Preset colors
 */
function sfb_get_brand_presets() {
  return [
    'modern_blue'       => '#0E45E9',
    'architect_gray'    => '#9AA0A6',
    'engineering_bold'  => '#0F5C2E',
    'clean_violet'      => '#7861FF',
  ];
}
