<?php
/**
 * Branding Settings Helper Functions
 *
 * Provides centralized brand settings management with new structured format
 *
 * @package SubmittalBuilder
 * @version 1.1.0
 */

if (!defined('ABSPATH')) exit;

/**
 * Get default brand settings
 *
 * @return array Brand settings with company, visual, and meta keys
 */
function sfb_brand_defaults() {
  return [
    'company' => [
      'name'     => get_bloginfo('name'),
      'address'  => '',
      'phone'    => '',
      'website'  => get_site_url(),
      'logo_id'  => 0,
      'logo_url' => '',
    ],
    'visual' => [
      'primary_color'  => '#0E45E9', // modern_blue default
      'include_cover'  => true,
      'footer_text'    => 'Generated by Submittal & Spec Sheet Builder',
      'preset_key'     => 'modern_blue',
    ],
    'white_label' => [
      'enabled'           => false,
      'custom_footer'     => '',
      'email_from_name'   => '',
      'email_from_address' => '',
      'show_subtle_credit' => false,
    ],
    '_meta' => [
      'version'    => '1.1.1',
      'updated_at' => current_time('mysql'),
    ],
  ];
}

/**
 * Sanitize brand settings input
 *
 * @param array $in Raw input data
 * @return array Sanitized brand settings
 */
function sfb_sanitize_brand_settings($in) {
  $defaults = sfb_brand_defaults();

  // Company data
  $company = [
    'name'     => sanitize_text_field($in['company']['name'] ?? $defaults['company']['name']),
    'address'  => sanitize_textarea_field($in['company']['address'] ?? $defaults['company']['address']),
    'phone'    => sanitize_text_field($in['company']['phone'] ?? $defaults['company']['phone']),
    'website'  => sanitize_text_field($in['company']['website'] ?? $defaults['company']['website']),
    'logo_id'  => absint($in['company']['logo_id'] ?? $defaults['company']['logo_id']),
    'logo_url' => esc_url_raw($in['company']['logo_url'] ?? $defaults['company']['logo_url']),
  ];

  // Visual settings
  $visual = [
    'primary_color' => preg_match('/^#([0-9a-f]{3}|[0-9a-f]{6})$/i', $in['visual']['primary_color'] ?? '')
                       ? $in['visual']['primary_color']
                       : $defaults['visual']['primary_color'],
    'include_cover' => !empty($in['visual']['include_cover']),
    'footer_text'   => sanitize_text_field($in['visual']['footer_text'] ?? $defaults['visual']['footer_text']),
    'preset_key'    => in_array($in['visual']['preset_key'] ?? '', ['modern_blue', 'architect_gray', 'engineering_bold', 'clean_violet', 'custom'])
                       ? $in['visual']['preset_key']
                       : 'custom',
  ];

  // White-label settings (Agency-only)
  $white_label = [
    'enabled'            => !empty($in['white_label']['enabled']),
    'custom_footer'      => sanitize_text_field($in['white_label']['custom_footer'] ?? $defaults['white_label']['custom_footer']),
    'email_from_name'    => sanitize_text_field($in['white_label']['email_from_name'] ?? $defaults['white_label']['email_from_name']),
    'email_from_address' => sanitize_email($in['white_label']['email_from_address'] ?? $defaults['white_label']['email_from_address']),
    'show_subtle_credit' => !empty($in['white_label']['show_subtle_credit']),
  ];

  // Meta
  $meta = [
    'version'    => '1.1.1',
    'updated_at' => current_time('mysql'),
  ];

  return [
    'company'     => $company,
    'visual'      => $visual,
    'white_label' => $white_label,
    '_meta'       => $meta,
  ];
}

/**
 * Get brand settings (with fallback to old format for migration)
 *
 * @return array Brand settings
 */
function sfb_get_brand_settings() {
  $brand = get_option('sfb_brand_settings', null);

  // If new format exists, use it
  if ($brand !== null && isset($brand['company']) && isset($brand['visual'])) {
    // Ensure logo_url is populated if logo_id exists
    if (!empty($brand['company']['logo_id']) && empty($brand['company']['logo_url'])) {
      $logo_url = wp_get_attachment_image_url($brand['company']['logo_id'], 'full');
      if ($logo_url) {
        $brand['company']['logo_url'] = $logo_url;
      }
    }
    return $brand;
  }

  // Migration: Check old format and convert
  $old = get_option('sfb_branding', []);
  if (!empty($old)) {
    $migrated = [
      'company' => [
        'name'     => $old['company_name'] ?? get_bloginfo('name'),
        'address'  => $old['company_address'] ?? '',
        'phone'    => $old['company_phone'] ?? '',
        'website'  => $old['company_website'] ?? get_site_url(),
        'logo_id'  => 0, // Old format didn't store ID
        'logo_url' => $old['logo_url'] ?? '',
      ],
      'visual' => [
        'primary_color'  => $old['primary_color'] ?? '#0E45E9',
        'include_cover'  => $old['cover_default'] ?? true,
        'footer_text'    => $old['footer_text'] ?? 'Generated by Submittal & Spec Sheet Builder',
        'preset_key'     => $old['brand_preset'] ?? 'custom',
      ],
      '_meta' => [
        'version'    => '1.1.0',
        'updated_at' => current_time('mysql'),
        'migrated_from' => 'sfb_branding',
      ],
    ];

    // Save migrated data
    update_option('sfb_brand_settings', $migrated, false);

    return $migrated;
  }

  // Return defaults if nothing exists
  return sfb_brand_defaults();
}

/**
 * Get preset color mappings
 *
 * @return array Preset colors
 */
function sfb_get_brand_presets() {
  return [
    'modern_blue'       => '#0E45E9',
    'architect_gray'    => '#9AA0A6',
    'engineering_bold'  => '#0F5C2E',
    'clean_violet'      => '#7861FF',
  ];
}

// ============================================================================
// AGENCY HELPERS (Client Handoff Mode)
// ============================================================================

/**
 * Check if Client Handoff Mode is enabled
 *
 * When enabled, hides Agency-specific features like:
 * - Agency Library
 * - Brand Presets management
 * - Demo Tools & Seeder
 *
 * @return bool True if handoff mode is enabled
 */
function sfb_is_client_handoff_mode() {
  // Only available for Agency tier
  if (!sfb_is_agency_license()) {
    return false;
  }

  // Check if handoff mode is enabled
  return (bool) get_option('sfb_client_handoff_mode', false);
}

// ============================================================================
// BRAND CREDIT HELPERS (Free tier branding)
// ============================================================================

/**
 * Check if white-label branding is enabled
 *
 * Requires Agency license AND white-label mode toggle to be enabled.
 * When enabled, all plugin branding is hidden from PDFs, emails, and frontend.
 *
 * @return bool True if white-label is enabled
 */
function sfb_is_white_label_enabled() {
  // Check if Agency license is active
  if (!SFB_Branding::is_agency_license()) {
    return false;
  }

  // Check if white-label mode is enabled in settings
  $brand_settings = sfb_get_brand_settings();

  // Check if white_label section exists and is enabled
  if (isset($brand_settings['white_label']['enabled'])) {
    return (bool) $brand_settings['white_label']['enabled'];
  }

  // Default: white-label is disabled
  return false;
}

/**
 * Generate branded credit HTML for various contexts
 *
 * This function provides tasteful, small credits for Free tier users.
 * Will be disabled when White-Label feature is enabled (Agency tier) unless
 * "show_subtle_credit" is enabled.
 *
 * @param string $context Context identifier (generic, pdf, email, frontend, tracking, admin)
 * @return string HTML credit string or empty if white-label enabled
 */
function sfb_brand_credit($context = 'generic') {
  // Check if white-label is enabled
  if (sfb_is_white_label_enabled()) {
    // Check if user wants to show subtle credit
    $brand_settings = sfb_get_brand_settings();
    $show_subtle_credit = !empty($brand_settings['white_label']['show_subtle_credit']);

    // If show_subtle_credit is enabled, show "Powered by" version (not on frontend)
    if ($show_subtle_credit && $context !== 'frontend') {
      $credit_text = 'Powered by Submittal & Spec Sheet Builder';
      $credit_url = 'https://webstuffguylabs.com/plugins/submittal-spec-sheet-builder/';

      return '<span class="sfb-credit sfb-credit--' . esc_attr($context) . ' sfb-credit--subtle">'
        . '<a href="' . esc_url($credit_url) . '" target="_blank" rel="noopener noreferrer" style="color: inherit; text-decoration: none; font-size: 10px; opacity: 0.6;">'
        . esc_html($credit_text)
        . '</a>'
        . '</span>';
    }

    // Otherwise, return empty (fully white-labeled)
    return '';
  }

  $site_name = get_bloginfo('name');
  $credit_text = 'Generated with Submittal & Spec Sheet Builder';
  $credit_url = 'https://webstuffguylabs.com/plugins/submittal-spec-sheet-builder/';

  // Allow filtering of credit text and URL
  $credit_text = apply_filters('sfb_brand_credit_text', $credit_text, $context, $site_name);
  $credit_url = apply_filters('sfb_brand_credit_url', $credit_url, $context);

  // Return linked credit with context-specific CSS class
  return '<span class="sfb-credit sfb-credit--' . esc_attr($context) . '">'
    . '<a href="' . esc_url($credit_url) . '" target="_blank" rel="noopener noreferrer" style="color: inherit; text-decoration: none;">'
    . esc_html($credit_text)
    . '</a>'
    . '</span>';
}

/**
 * Generate plain-text credit for contexts that don't support HTML
 *
 * @param string $context Context identifier
 * @return string Plain text credit or empty if white-label enabled
 */
function sfb_brand_credit_plain($context = 'generic') {
  // Check if white-label is enabled
  if (sfb_is_white_label_enabled()) {
    // Check if user wants to show subtle credit
    $brand_settings = sfb_get_brand_settings();
    $show_subtle_credit = !empty($brand_settings['white_label']['show_subtle_credit']);

    // If show_subtle_credit is enabled, return "Powered by" version (not on frontend)
    if ($show_subtle_credit && $context !== 'frontend') {
      return 'Powered by Submittal & Spec Sheet Builder';
    }

    // Otherwise, check if custom footer text is set
    if (!empty($brand_settings['white_label']['custom_footer'])) {
      return $brand_settings['white_label']['custom_footer'];
    }

    // Otherwise, return empty (fully white-labeled)
    return '';
  }

  $site_name = get_bloginfo('name');
  $credit_text = 'Generated with Submittal & Spec Sheet Builder';

  // Allow filtering of credit text
  $credit_text = apply_filters('sfb_brand_credit_text', $credit_text, $context, $site_name);

  return $credit_text;
}
